## APRENDIZAGEM SUPERVISIONADAS: CLASSIFICAÇÃO

In [4]:
# INDICE 
conteudo = {'APRENDIZAGEM SUPERVISIONADAS: CLASSIFICAÇÃO': 
                ['SOBRE O PROJETO',
                'SIGNIFICADO DOS ATRIBUTOS DA PLANILHA',
                 'Transformando as variáveis categóricas nominais em variáveis categóricas ordinais'
                 'ATRIBUTOS PREVISORES e ALVOS',
                 'ANALISE DAS ESCALAS DOS ATRIBUTOS (ESCALONAMENTO)',
                 'CODIFICAÇÃO DE VARIAVEIS CATEGORICAS',
                 'LABELENCODER: transformação de variaveis categoricas em numericas',
                 'ONE HOT ENCODER -> Criação de variaveis Dummy(ficticia)',
                 'STANDARD SCALER'
                 'RESUMO PRÉ-PROCESSAMENTO',
                 'Redução de Dimensionalidade'
                'BASE DE TREINO E TESTE',
                'NAIVE BAYES',
                'SVM - máquina de Vetor de suporte',
                'Resultado Final']}

# Imprime os títulos e subtítulos com seus respectivos índices
for i, (titulo, subtitulos) in enumerate(conteudo.items()):
    print(f"{i}. {titulo}")
    for j, subtitulo in enumerate(subtitulos):
        print(f"   {i}.{j+1}. {subtitulo}")



0. APRENDIZAGEM SUPERVISIONADAS: CLASSIFICAÇÃO
   0.1. SOBRE O PROJETO
   0.2. SIGNIFICADO DOS ATRIBUTOS DA PLANILHA
   0.3. Transformando as variáveis categóricas nominais em variáveis categóricas ordinaisATRIBUTOS PREVISORES e ALVOS
   0.4. ANALISE DAS ESCALAS DOS ATRIBUTOS (ESCALONAMENTO)
   0.5. CODIFICAÇÃO DE VARIAVEIS CATEGORICAS
   0.6. LABELENCODER: transformação de variaveis categoricas em numericas
   0.7. ONE HOT ENCODER -> Criação de variaveis Dummy(ficticia)
   0.8. STANDARD SCALERRESUMO PRÉ-PROCESSAMENTO
   0.9. Redução de DimensionalidadeBASE DE TREINO E TESTE
   0.10. NAIVE BAYES
   0.11. SVM - máquina de Vetor de suporte
   0.12. Resultado Final


### SOBRE O PROJETO
- Este projeto tem por objetivo desenvolver um algoritmo de machine learn para prever a tendência de Uma pessoa em desenvolver algum tipo de doença cardiaca com base em alguns fatores clinicos.
    

In [24]:
import pandas as pd
import numpy as np
tabela = pd.read_csv(r'Heart_Dados_Tratados.csv', sep=",")
tabela

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
0     40   M           ATA        140        289.0          0     Normal   
1     49   F           NAP        160        180.0          0     Normal   
2     37   M           ATA        130        283.0          0         ST   
3     48   F           ASY        138        214.0          0     Normal   
4     54   M           NAP        150        195.0          0     Normal   
..   ...  ..           ...        ...          ...        ...        ...   
912   45   M            TA        110        264.0          0     Normal   
913   68   M           ASY        144        193.0          1     Normal   
914   57   M           ASY        130        131.0          0     Normal   
915   57   F           ATA        130        236.0          0        LVH   
916   38   M           NAP        138        175.0          0     Normal   

     MaxHR ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0      172              N      0.0       Up             0  
1      156              N      1.0     Flat             1  
2       98              N      0.0       Up             0  
3      108              Y      1.5     Flat             1  
4      122              N      0.0       Up             0  
..     ...            ...      ...      ...           ...  
912    132              N      1.2     Flat             1  
913    141              N      3.4     Flat             1  
914    115              Y      1.2     Flat             1  
915    174              N      0.0     Flat             1  
916    173              N      0.0       Up             0  

[917 rows x 12 columns]

 ## SIGNIFICADO DOS ATRIBUTOS DA PLANILHA

- Chest Pain Type-tipo de dor no peito (0-TA angina tipica: 1-ATA angina atipica 2-NAP dor não angmose 3-ASY

- Resting BP-pressão sanguinea em repouso (mmHg)

- Cholesterol colesterol sérico (mg/dl)

- Fasting BS açúcar no sangue em jejurn (mg/dl) 0 Fasting BS 120 mg/at (não diabetico) 1.Fact

- Resting ECG eletrocardiograma em repouso (0-Normal 1-51 Anormaldade da

- Max HR-frequencia cardiaca maxima

- Exercise Angina Angina induzida pdxercicio (0-No: 1-Sim)

- OlD Peak-> Depressão de ST induzida por exercico em relação ao pou

- ST_Slop -> inlcinação do segmento ST (0=UP;2=Flat;2=Down)

## Transformando as variáveis categóricas nominais em variáveis categóricas ordinais

In [26]:
tabela2 = pd.DataFrame.copy(tabela)

In [27]:
tabela2['Sex'].replace({'M':0, 'F': 1}, inplace=True)
tabela2['ChestPainType'].replace({'TA':0, 'ATA': 1, 'NAP':2, 'ASY': 3}, inplace=True)
tabela2['RestingECG'].replace({'Normal':0, 'ST': 1, 'LVH':2}, inplace=True)
tabela2['ExerciseAngina'].replace({'N':0, 'Y': 1}, inplace=True)
tabela2['ST_Slope'].replace({'Up':0, 'Flat': 1, 'Down':2}, inplace=True)

In [28]:
## ESCALONAMENTO MANUAL
tabela2.head()

Age  Sex  ChestPainType  RestingBP  Cholesterol  FastingBS  RestingECG  \
0   40    0              1        140        289.0          0           0   
1   49    1              2        160        180.0          0           0   
2   37    0              1        130        283.0          0           1   
3   48    1              3        138        214.0          0           0   
4   54    0              2        150        195.0          0           0   

   MaxHR  ExerciseAngina  Oldpeak  ST_Slope  HeartDisease  
0    172               0      0.0         0             0  
1    156               0      1.0         1             1  
2     98               0      0.0         0             0  
3    108               1      1.5         1             1  
4    122               0      0.0         0             0

In [29]:
tabela2.dtypes

Age                 int64
Sex                 int64
ChestPainType       int64
RestingBP           int64
Cholesterol       float64
FastingBS           int64
RestingECG          int64
MaxHR               int64
ExerciseAngina      int64
Oldpeak           float64
ST_Slope            int64
HeartDisease        int64
dtype: object

In [30]:
tabela2.describe()

Age         Sex  ChestPainType   RestingBP  Cholesterol  \
count  917.000000  917.000000     917.000000  917.000000   917.000000   
mean    53.509269    0.210469       2.251908  132.540894   244.635389   
std      9.437636    0.407864       0.931502   17.999749    53.347125   
min     28.000000    0.000000       0.000000   80.000000    85.000000   
25%     47.000000    0.000000       2.000000  120.000000   214.000000   
50%     54.000000    0.000000       3.000000  130.000000   244.635389   
75%     60.000000    0.000000       3.000000  140.000000   267.000000   
max     77.000000    1.000000       3.000000  200.000000   603.000000   

        FastingBS  RestingECG       MaxHR  ExerciseAngina     Oldpeak  \
count  917.000000  917.000000  917.000000      917.000000  917.000000   
mean     0.233370    0.604144  136.789531        0.404580    0.886696   
std      0.423206    0.806161   25.467129        0.491078    1.066960   
min      0.000000    0.000000   60.000000        0.000000   -2.600000   
25%      0.000000    0.000000  120.000000        0.000000    0.000000   
50%      0.000000    0.000000  138.000000        0.000000    0.600000   
75%      0.000000    1.000000  156.000000        1.000000    1.500000   
max      1.000000    2.000000  202.000000        1.000000    6.200000   

        ST_Slope  HeartDisease  
count  917.00000    917.000000  
mean     0.63795      0.552890  
std      0.60727      0.497466  
min      0.00000      0.000000  
25%      0.00000      0.000000  
50%      1.00000      1.000000  
75%      1.00000      1.000000  
max      2.00000      1.000000

In [31]:
 #### VERIFICAÇÂO DAS FERRAMENTAS DISPONIVEIS PARA O M.L

In [32]:
## Conferirndo se a biblioteca se esta instalada
!pip show scikit-learn

Name: scikit-learn
Version: 1.0.2
Summary: A set of python modules for machine learning and data mining
Home-page: http://scikit-learn.org
Author: 
Author-email: 
License: new BSD
Location: c:\users\leona\anaconda3\lib\site-packages
Requires: joblib, numpy, scipy, threadpoolctl
Required-by: scikit-learn-intelex


## ATRIBUTOS PREVISORES e ALVOS ###

In [33]:
## tabela em forma de indices[índex]
## processo inicial para ser usado na maquina ML
previsores = tabela2.iloc[:,0:11].values
previsores

array([[40. ,  0. ,  1. , ...,  0. ,  0. ,  0. ],
       [49. ,  1. ,  2. , ...,  0. ,  1. ,  1. ],
       [37. ,  0. ,  1. , ...,  0. ,  0. ,  0. ],
       ...,
       [57. ,  0. ,  3. , ...,  1. ,  1.2,  1. ],
       [57. ,  1. ,  1. , ...,  0. ,  0. ,  1. ],
       [38. ,  0. ,  2. , ...,  0. ,  0. ,  0. ]])

In [34]:
previsores.shape 

(917, 11)

In [35]:
# Determinar o ALVO
alvo = tabela2.iloc[:,11].values
alvo

array([0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,

In [36]:
alvo.shape

(917,)

### ANALISE DAS  ESCALAS DOS ATRIBUTOS (ESCALONAMENTO)

In [41]:
## algumas colunas não tem ESCALAS adequados para o machine learn, ex numeros 85, 136,  etc
## ESCALONAMENTO 1
from sklearn.preprocessing import StandardScaler
tabela2.describe()

Age         Sex  ChestPainType   RestingBP  Cholesterol  \
count  917.000000  917.000000     917.000000  917.000000   917.000000   
mean    53.509269    0.210469       2.251908  132.540894   244.635389   
std      9.437636    0.407864       0.931502   17.999749    53.347125   
min     28.000000    0.000000       0.000000   80.000000    85.000000   
25%     47.000000    0.000000       2.000000  120.000000   214.000000   
50%     54.000000    0.000000       3.000000  130.000000   244.635389   
75%     60.000000    0.000000       3.000000  140.000000   267.000000   
max     77.000000    1.000000       3.000000  200.000000   603.000000   

        FastingBS  RestingECG       MaxHR  ExerciseAngina     Oldpeak  \
count  917.000000  917.000000  917.000000      917.000000  917.000000   
mean     0.233370    0.604144  136.789531        0.404580    0.886696   
std      0.423206    0.806161   25.467129        0.491078    1.066960   
min      0.000000    0.000000   60.000000        0.000000   -2.600000   
25%      0.000000    0.000000  120.000000        0.000000    0.000000   
50%      0.000000    0.000000  138.000000        0.000000    0.600000   
75%      0.000000    1.000000  156.000000        1.000000    1.500000   
max      1.000000    2.000000  202.000000        1.000000    6.200000   

        ST_Slope  HeartDisease  
count  917.00000    917.000000  
mean     0.63795      0.552890  
std      0.60727      0.497466  
min      0.00000      0.000000  
25%      0.00000      0.000000  
50%      1.00000      1.000000  
75%      1.00000      1.000000  
max      2.00000      1.000000

In [42]:
## Padronização (utiliza a media e o desvio padroo como referencia)
## Normalização ( utiliza os valores maximos e minimo como referencia)

In [43]:
## PREVISOSR ESCALONADOS
previsores_esc = StandardScaler().fit_transform(previsores)

In [44]:
previsores_esc

array([[-1.43220634, -0.51630861, -1.34470119, ..., -0.82431012,
        -0.83150225, -1.05109458],
       [-0.47805725,  1.9368261 , -0.27058012, ..., -0.82431012,
         0.10625149,  0.59651863],
       [-1.75025603, -0.51630861, -1.34470119, ..., -0.82431012,
        -0.83150225, -1.05109458],
       ...,
       [ 0.37007527, -0.51630861,  0.80354095, ...,  1.21313565,
         0.29380223,  0.59651863],
       [ 0.37007527,  1.9368261 , -1.34470119, ..., -0.82431012,
        -0.83150225,  0.59651863],
       [-1.64423947, -0.51630861, -0.27058012, ..., -0.82431012,
        -0.83150225, -1.05109458]])

In [45]:
## TRANSFORMAR EM DATAFRAME PARA AVALIAÇÃO.
import pandas as pd
previsoresDF = pd.DataFrame(previsores_esc) 
previsoresDF


0         1         2         3         4         5         6   \
0   -1.432206 -0.516309 -1.344701  0.414627  0.832075 -0.551733 -0.749818   
1   -0.478057  1.936826 -0.270580  1.526360 -1.212261 -0.551733 -0.749818   
2   -1.750256 -0.516309 -1.344701 -0.141240  0.719543 -0.551733  0.491306   
3   -0.584074  1.936826  0.803541  0.303453 -0.574578 -0.551733 -0.749818   
4    0.052026 -0.516309 -0.270580  0.970493 -0.930931 -0.551733 -0.749818   
..        ...       ...       ...       ...       ...       ...       ...   
912 -0.902124 -0.516309 -2.418822 -1.252973  0.363191 -0.551733 -0.749818   
913  1.536257 -0.516309  0.803541  0.636973 -0.968441  1.812470 -0.749818   
914  0.370075 -0.516309  0.803541 -0.141240 -2.131275 -0.551733 -0.749818   
915  0.370075  1.936826 -1.344701 -0.141240 -0.161960 -0.551733  1.732430   
916 -1.644239 -0.516309 -0.270580  0.303453 -1.306038 -0.551733 -0.749818   

           7         8         9         10  
0    1.383339 -0.824310 -0.831502 -1.051095  
1    0.754736 -0.824310  0.106251  0.596519  
2   -1.523953 -0.824310 -0.831502 -1.051095  
3   -1.131075  1.213136  0.575128  0.596519  
4   -0.581047 -0.824310 -0.831502 -1.051095  
..        ...       ...       ...       ...  
912 -0.188170 -0.824310  0.293802  0.596519  
913  0.165420 -0.824310  2.356860  0.596519  
914 -0.856061  1.213136  0.293802  0.596519  
915  1.461915 -0.824310 -0.831502  0.596519  
916  1.422627 -0.824310 -0.831502 -1.051095  

[917 rows x 11 columns]

In [46]:
## ANTES
tabela2.describe()

Age         Sex  ChestPainType   RestingBP  Cholesterol  \
count  917.000000  917.000000     917.000000  917.000000   917.000000   
mean    53.509269    0.210469       2.251908  132.540894   244.635389   
std      9.437636    0.407864       0.931502   17.999749    53.347125   
min     28.000000    0.000000       0.000000   80.000000    85.000000   
25%     47.000000    0.000000       2.000000  120.000000   214.000000   
50%     54.000000    0.000000       3.000000  130.000000   244.635389   
75%     60.000000    0.000000       3.000000  140.000000   267.000000   
max     77.000000    1.000000       3.000000  200.000000   603.000000   

        FastingBS  RestingECG       MaxHR  ExerciseAngina     Oldpeak  \
count  917.000000  917.000000  917.000000      917.000000  917.000000   
mean     0.233370    0.604144  136.789531        0.404580    0.886696   
std      0.423206    0.806161   25.467129        0.491078    1.066960   
min      0.000000    0.000000   60.000000        0.000000   -2.600000   
25%      0.000000    0.000000  120.000000        0.000000    0.000000   
50%      0.000000    0.000000  138.000000        0.000000    0.600000   
75%      0.000000    1.000000  156.000000        1.000000    1.500000   
max      1.000000    2.000000  202.000000        1.000000    6.200000   

        ST_Slope  HeartDisease  
count  917.00000    917.000000  
mean     0.63795      0.552890  
std      0.60727      0.497466  
min      0.00000      0.000000  
25%      0.00000      0.000000  
50%      1.00000      1.000000  
75%      1.00000      1.000000  
max      2.00000      1.000000

In [47]:
## DEPOIS 
previsoresDF.describe()

0             1             2             3             4   \
count  9.170000e+02  9.170000e+02  9.170000e+02  9.170000e+02  9.170000e+02   
mean   1.025231e-15  3.099423e-17  6.552979e-16  7.554844e-16 -1.929875e-16   
std    1.000546e+00  1.000546e+00  1.000546e+00  1.000546e+00  1.000546e+00   
min   -2.704405e+00 -5.163086e-01 -2.418822e+00 -2.920572e+00 -2.994023e+00   
25%   -6.900904e-01 -5.163086e-01 -2.705801e-01 -6.971063e-01 -5.745784e-01   
50%    5.202558e-02 -5.163086e-01  8.035410e-01 -1.412398e-01  0.000000e+00   
75%    6.881250e-01 -5.163086e-01  8.035410e-01  4.146267e-01  4.194568e-01   
max    2.490407e+00  1.936826e+00  8.035410e-01  3.749826e+00  6.721265e+00   

                 5             6             7             8             9   \
count  9.170000e+02  9.170000e+02  9.170000e+02  9.170000e+02  9.170000e+02   
mean  -2.808852e-17  1.954089e-16 -4.881591e-16  1.280933e-16  1.217976e-16   
std    1.000546e+00  1.000546e+00  1.000546e+00  1.000546e+00  1.000546e+00   
min   -5.517333e-01 -7.498176e-01 -3.016886e+00 -8.243101e-01 -3.269662e+00   
25%   -5.517333e-01 -7.498176e-01 -6.596226e-01 -8.243101e-01 -8.315022e-01   
50%   -5.517333e-01 -7.498176e-01  4.755658e-02 -8.243101e-01 -2.688500e-01   
75%   -5.517333e-01  4.913064e-01  7.547357e-01  1.213136e+00  5.751284e-01   
max    1.812470e+00  1.732430e+00  2.561971e+00  1.213136e+00  4.982571e+00   

                 10  
count  9.170000e+02  
mean   4.770206e-17  
std    1.000546e+00  
min   -1.051095e+00  
25%   -1.051095e+00  
50%    5.965186e-01  
75%    5.965186e-01  
max    2.244132e+00

## CODIFICAÇÃO DE VARIAVEIS CATEGORICAS

In [48]:
## PROCESSO DE ESCOLONAGEM 2 COM LABEL ENCONDER

### LABEL ENCODER: transformação de variaveis categoricas em numericas

In [49]:
from sklearn.preprocessing import LabelEncoder 

In [50]:
tabela.head(10)

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  MaxHR  \
0   40   M           ATA        140        289.0          0     Normal    172   
1   49   F           NAP        160        180.0          0     Normal    156   
2   37   M           ATA        130        283.0          0         ST     98   
3   48   F           ASY        138        214.0          0     Normal    108   
4   54   M           NAP        150        195.0          0     Normal    122   
5   39   M           NAP        120        339.0          0     Normal    170   
6   45   F           ATA        130        237.0          0     Normal    170   
7   54   M           ATA        110        208.0          0     Normal    142   
8   37   M           ASY        140        207.0          0     Normal    130   
9   48   F           ATA        120        284.0          0     Normal    120   

  ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0              N      0.0       Up             0  
1              N      1.0     Flat             1  
2              N      0.0       Up             0  
3              Y      1.5     Flat             1  
4              N      0.0       Up             0  
5              N      0.0       Up             0  
6              N      0.0       Up             0  
7              N      0.0       Up             0  
8              Y      1.5     Flat             1  
9              N      0.0       Up             0

In [51]:
## preciso encodaros e preparar algumas classes categoricas 
previsores2 = tabela.iloc[:,0:11].values
previsores2

array([[40, 'M', 'ATA', ..., 'N', 0.0, 'Up'],
       [49, 'F', 'NAP', ..., 'N', 1.0, 'Flat'],
       [37, 'M', 'ATA', ..., 'N', 0.0, 'Up'],
       ...,
       [57, 'M', 'ASY', ..., 'Y', 1.2, 'Flat'],
       [57, 'F', 'ATA', ..., 'N', 0.0, 'Flat'],
       [38, 'M', 'NAP', ..., 'N', 0.0, 'Up']], dtype=object)

In [52]:
## preciso
previsores2[:,1] = LabelEncoder().fit_transform(previsores[:,1])

In [53]:
previsores2

array([[40, 0, 'ATA', ..., 'N', 0.0, 'Up'],
       [49, 1, 'NAP', ..., 'N', 1.0, 'Flat'],
       [37, 0, 'ATA', ..., 'N', 0.0, 'Up'],
       ...,
       [57, 0, 'ASY', ..., 'Y', 1.2, 'Flat'],
       [57, 1, 'ATA', ..., 'N', 0.0, 'Flat'],
       [38, 0, 'NAP', ..., 'N', 0.0, 'Up']], dtype=object)

In [54]:
## tranformar todas outras para o processo de machine learn
previsores2[:,2] = LabelEncoder().fit_transform(previsores[:,2])
previsores2[:,6] = LabelEncoder().fit_transform(previsores[:,6])
previsores2[:,8] = LabelEncoder().fit_transform(previsores[:,8])
previsores2[:,10] = LabelEncoder().fit_transform(previsores[:,10])

In [55]:
previsores2

array([[40, 0, 1, ..., 0, 0.0, 0],
       [49, 1, 2, ..., 0, 1.0, 1],
       [37, 0, 1, ..., 0, 0.0, 0],
       ...,
       [57, 0, 3, ..., 1, 1.2, 1],
       [57, 1, 1, ..., 0, 0.0, 1],
       [38, 0, 2, ..., 0, 0.0, 0]], dtype=object)

### ONE HOT ENCONDER 

In [56]:
from sklearn.preprocessing import OneHotEncoder 
from sklearn.compose import ColumnTransformer

In [9]:
## DUVIDA PARA VER QUAL SÃO OS PARAMETROS - ANALAISE PARA MELHOR FAZER O USO
ColumnTransformer?

In [40]:
### sobre essa FUNÇÂO : ColumnTransformer

## name : nome dado a transfomação
## transformer: tipo de estimador(OneHotEncoder)
## column:colunas que serao transformadas
## remainder> o que acontecera com o restante das colunas não relacionais:
# (1) DROP= exclui as outras colunas, 2 
# (2) passthrough= mantem as outras colunas : drop é defaut
## sparse_threshold: parametros de classificação de matrizes esparsas. default é 0.3
## n_jobs > numeros de trabalhos a serem executados em paralelo. default é nenhum
## TRANSFORMER_WEIGHTS:  Definição de pesos aos transformadores
## VERBOSE:  default é false, se for True a execução é apresentada na tela



In [57]:
# AS COLUNAS QUE AINDA PRECISAM SER ESCALONADAS
previsores3 = ColumnTransformer(transformers=[('OneHot', OneHotEncoder(), [1,2,6,8,10])],
                              remainder='passthrough').fit_transform(previsores2)
previsores3

array([[1.0, 0.0, 0.0, ..., 0, 172, 0.0],
       [0.0, 1.0, 0.0, ..., 0, 156, 1.0],
       [1.0, 0.0, 0.0, ..., 0, 98, 0.0],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 115, 1.2],
       [0.0, 1.0, 0.0, ..., 0, 174, 0.0],
       [1.0, 0.0, 0.0, ..., 0, 173, 0.0]], dtype=object)

In [58]:
## aumentou a quantidade de colunas
#o One Hot Encoder aumenta o número de colunas no conjunto de dados, o que pode tornar a análise mais complexa e aumentar o tempo de processamento. No entanto, esse é um trade-off que pode valer a pena para modelos que exigem esse tipo de representação dos dados categóricos. Além disso, existem técnicas de redução de dimensionalidade, como PCA, que podem ser aplicadas para lidar com conjuntos de dados com muitas colunas.
previsores3.shape

(917, 20)

In [59]:
previsores3df = pd.DataFrame(previsores3)
previsores3df.head()

0    1    2    3    4    5    6    7    8    9    10   11   12   13  14  \
0  1.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  40   
1  0.0  1.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  49   
2  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  1.0  0.0  0.0  37   
3  0.0  1.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  48   
4  1.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  54   

    15     16 17   18   19  
0  140  289.0  0  172  0.0  
1  160  180.0  0  156  1.0  
2  130  283.0  0   98  0.0  
3  138  214.0  0  108  1.5  
4  150  195.0  0  122  0.0

In [60]:
tabela.head()

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  MaxHR  \
0   40   M           ATA        140        289.0          0     Normal    172   
1   49   F           NAP        160        180.0          0     Normal    156   
2   37   M           ATA        130        283.0          0         ST     98   
3   48   F           ASY        138        214.0          0     Normal    108   
4   54   M           NAP        150        195.0          0     Normal    122   

  ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0              N      0.0       Up             0  
1              N      1.0     Flat             1  
2              N      0.0       Up             0  
3              Y      1.5     Flat             1  
4              N      0.0       Up             0

### STANDARD SCALER

In [61]:
## ALGUMAS COLUNAS COMO : 15,16,18,19 precisa fazer um escalonamento
# se nao pode dar erros
from sklearn.preprocessing import StandardScaler

In [62]:
previsores3_esc = StandardScaler().fit_transform(previsores3)

In [63]:
previsores3_esc

array([[ 0.51630861, -0.51630861, -0.22981048, ..., -0.55173333,
         1.38333943, -0.83150225],
       [-1.9368261 ,  1.9368261 , -0.22981048, ..., -0.55173333,
         0.75473573,  0.10625149],
       [ 0.51630861, -0.51630861, -0.22981048, ..., -0.55173333,
        -1.52395266, -0.83150225],
       ...,
       [ 0.51630861, -0.51630861, -0.22981048, ..., -0.55173333,
        -0.85606123,  0.29380223],
       [-1.9368261 ,  1.9368261 , -0.22981048, ..., -0.55173333,
         1.46191489, -0.83150225],
       [ 0.51630861, -0.51630861, -0.22981048, ..., -0.55173333,
         1.42262716, -0.83150225]])

In [64]:
## passando para o DATA.FRAME
previsores3df = pd.DataFrame(previsores3_esc)
previsores3df

0         1         2         3         4         5         6   \
0    0.516309 -0.516309 -0.229810  2.073784 -0.531524 -1.085425  0.815013   
1   -1.936826  1.936826 -0.229810 -0.482210  1.881384 -1.085425  0.815013   
2    0.516309 -0.516309 -0.229810  2.073784 -0.531524 -1.085425 -1.226974   
3   -1.936826  1.936826 -0.229810 -0.482210 -0.531524  0.921298  0.815013   
4    0.516309 -0.516309 -0.229810 -0.482210  1.881384 -1.085425  0.815013   
..        ...       ...       ...       ...       ...       ...       ...   
912  0.516309 -0.516309  4.351412 -0.482210 -0.531524 -1.085425  0.815013   
913  0.516309 -0.516309 -0.229810 -0.482210 -0.531524  0.921298  0.815013   
914  0.516309 -0.516309 -0.229810 -0.482210 -0.531524  0.921298  0.815013   
915 -1.936826  1.936826 -0.229810  2.073784 -0.531524 -1.085425 -1.226974   
916  0.516309 -0.516309 -0.229810 -0.482210  1.881384 -1.085425  0.815013   

           7         8         9         10        11        12        13  \
0   -0.490781 -0.507826  0.824310 -0.824310  1.149573 -1.001091 -0.271607   
1   -0.490781 -0.507826  0.824310 -0.824310 -0.869888  0.998910 -0.271607   
2    2.037569 -0.507826  0.824310 -0.824310  1.149573 -1.001091 -0.271607   
3   -0.490781 -0.507826 -1.213136  1.213136 -0.869888  0.998910 -0.271607   
4   -0.490781 -0.507826  0.824310 -0.824310  1.149573 -1.001091 -0.271607   
..        ...       ...       ...       ...       ...       ...       ...   
912 -0.490781 -0.507826  0.824310 -0.824310 -0.869888  0.998910 -0.271607   
913 -0.490781 -0.507826  0.824310 -0.824310 -0.869888  0.998910 -0.271607   
914 -0.490781 -0.507826 -1.213136  1.213136 -0.869888  0.998910 -0.271607   
915 -0.490781  1.969177  0.824310 -0.824310 -0.869888  0.998910 -0.271607   
916 -0.490781 -0.507826  0.824310 -0.824310  1.149573 -1.001091 -0.271607   

           14        15        16        17        18        19  
0   -1.432206  0.414627  0.832075 -0.551733  1.383339 -0.831502  
1   -0.478057  1.526360 -1.212261 -0.551733  0.754736  0.106251  
2   -1.750256 -0.141240  0.719543 -0.551733 -1.523953 -0.831502  
3   -0.584074  0.303453 -0.574578 -0.551733 -1.131075  0.575128  
4    0.052026  0.970493 -0.930931 -0.551733 -0.581047 -0.831502  
..        ...       ...       ...       ...       ...       ...  
912 -0.902124 -1.252973  0.363191 -0.551733 -0.188170  0.293802  
913  1.536257  0.636973 -0.968441  1.812470  0.165420  2.356860  
914  0.370075 -0.141240 -2.131275 -0.551733 -0.856061  0.293802  
915  0.370075 -0.141240 -0.161960 -0.551733  1.461915 -0.831502  
916 -1.644239  0.303453 -1.306038 -0.551733  1.422627 -0.831502  

[917 rows x 20 columns]

In [65]:
previsores3df.describe()

0             1             2             3             4   \
count  9.170000e+02  9.170000e+02  9.170000e+02  9.170000e+02  9.170000e+02   
mean   2.962613e-16 -2.985616e-16  2.330015e-16 -8.105718e-16  1.117003e-15   
std    1.000546e+00  1.000546e+00  1.000546e+00  1.000546e+00  1.000546e+00   
min   -1.936826e+00 -5.163086e-01 -2.298105e-01 -4.822104e-01 -5.315237e-01   
25%    5.163086e-01 -5.163086e-01 -2.298105e-01 -4.822104e-01 -5.315237e-01   
50%    5.163086e-01 -5.163086e-01 -2.298105e-01 -4.822104e-01 -5.315237e-01   
75%    5.163086e-01 -5.163086e-01 -2.298105e-01 -4.822104e-01 -5.315237e-01   
max    5.163086e-01  1.936826e+00  4.351412e+00  2.073784e+00  1.881384e+00   

                 5             6             7             8             9   \
count  9.170000e+02  9.170000e+02  9.170000e+02  9.170000e+02  9.170000e+02   
mean  -8.034286e-16 -4.690299e-16 -4.492953e-16 -3.319531e-15  8.402342e-17   
std    1.000546e+00  1.000546e+00  1.000546e+00  1.000546e+00  1.000546e+00   
min   -1.085425e+00 -1.226974e+00 -4.907810e-01 -5.078263e-01 -1.213136e+00   
25%   -1.085425e+00 -1.226974e+00 -4.907810e-01 -5.078263e-01 -1.213136e+00   
50%    9.212982e-01  8.150134e-01 -4.907810e-01 -5.078263e-01  8.243101e-01   
75%    9.212982e-01  8.150134e-01 -4.907810e-01 -5.078263e-01  8.243101e-01   
max    9.212982e-01  8.150134e-01  2.037569e+00  1.969177e+00  8.243101e-01   

                 10            11            12            13            14  \
count  9.170000e+02  9.170000e+02  9.170000e+02  9.170000e+02  9.170000e+02   
mean  -8.402342e-17 -9.661483e-17 -4.561963e-16 -1.212649e-15  1.050172e-15   
std    1.000546e+00  1.000546e+00  1.000546e+00  1.000546e+00  1.000546e+00   
min   -8.243101e-01 -8.698879e-01 -1.001091e+00 -2.716072e-01 -2.704405e+00   
25%   -8.243101e-01 -8.698879e-01 -1.001091e+00 -2.716072e-01 -6.900904e-01   
50%   -8.243101e-01 -8.698879e-01  9.989101e-01 -2.716072e-01  5.202558e-02   
75%    1.213136e+00  1.149573e+00  9.989101e-01 -2.716072e-01  6.881250e-01   
max    1.213136e+00  1.149573e+00  9.989101e-01  3.681787e+00  2.490407e+00   

                 15            16            17            18            19  
count  9.170000e+02  9.170000e+02  9.170000e+02  9.170000e+02  9.170000e+02  
mean   7.537288e-16  3.070850e-15 -9.930261e-16 -4.881591e-16 -1.234926e-17  
std    1.000546e+00  1.000546e+00  1.000546e+00  1.000546e+00  1.000546e+00  
min   -2.920572e+00 -2.994023e+00 -5.517333e-01 -3.016886e+00 -3.269662e+00  
25%   -6.971063e-01 -5.745784e-01 -5.517333e-01 -6.596226e-01 -8.315022e-01  
50%   -1.412398e-01  3.198360e-15 -5.517333e-01  4.755658e-02 -2.688500e-01  
75%    4.146267e-01  4.194568e-01 -5.517333e-01  7.547357e-01  5.751284e-01  
max    3.749826e+00  6.721265e+00  1.812470e+00  2.561971e+00  4.982571e+00

## RESUMO PRÉ-PROCESSAMENTO

- alvo = variável que se pretende atingir (tem ou não doença cardíaca).

- previsores = conjunto de variáveis previsoras com as variáveis categóricas transformadas em numéricas manualmente, sem escalonar.

- previsores_esc = conjunto de variáveis previsoras com as variáveis categóricas transformadas em numéricas, escalonada.

- previsores2 = conjunto de variáveis previsoras com as variáveis categóricas transformadas em numéricas pelo labelencoder.

- previsores3 = conjunto de variáveis previsoras transformadas pelo labelencoder e onehotencoder, sem escalonar.

- previsores3_esc = conjunto de variáveis previsoras transformadas pelo labelencoder e onehotencoder escalonada.

## Redução de Dimensionalidade

In [ ]:
### SOBRE ESSA TECNICA
## uma técnica utilizada para reduzir o número de variáveis ou recursos (features) em um 
# conjunto de dados. Ela tem como objetivo simplificar a representação dos dados, 
# removendo características irrelevantes, redundantes ou correlacionadas, e, 
# assim, melhorar a eficiência computacional e o desempenho dos modelos de machine learning.

###### ANALISE DOS COMPONENTES PRINCIPAIS ( PCA ) - (não supervisionado)

In [44]:
# seleção de caracteristica: seleciona os melhores atributos e utiliza sem transformações.
# Extração de caracteristicas: Encontra os relacionamentos dos melhores atributos e cria novos atributos
# -> é um algoritmo de aprendizagem não supervisionada, aplica em dados linearmente separaveis.

In [66]:
from sklearn.decomposition import PCA

In [13]:
PCA?
## n_componentes = pergunta par quantas colunas desejo fazer no caso de 11 para 8
# svd_solver -> automaticamente seleciona a melhor opçao nesta selecão(recomendado), 

In [67]:
pca = PCA(n_components=4, svd_solver='arpack')

In [68]:
previsores_pca = pca.fit_transform(previsores2)

In [69]:
previsores_pca.shape

(917, 4)

In [70]:
# components principais
previsores_pca

array([[  44.01031323,  -36.16368188,   10.64655418,   -9.4858855 ],
       [ -63.99070205,  -13.9285156 ,   31.68531903,   -5.3197523 ],
       [  38.53828121,   33.89882653,  -12.48258193,  -21.52677046],
       ...,
       [-113.34768547,   23.48739283,   -2.51236375,    1.14310997],
       [  -9.11479572,  -35.9101508 ,    4.82792119,    9.14499845],
       [ -70.01231135,  -35.67713061,   12.10297998,  -10.53005398]])

In [71]:
# razão das variaveis explicativas
pca.explained_variance_ratio_
## aqui essa função consegue explicar a variavel previsores em
# 72% + 17%, 8%, 1% 

array([0.72844082, 0.1718306 , 0.08121793, 0.01767869])

In [73]:
# soma das variaveis explicativas - total -> 99,9%
pca.explained_variance_ratio_.sum()

0.9991680439746077

## BASE  DE TREINO E TESTE

In [1]:
from sklearn.model_selection import train_test_split

In [ ]:
train_test_split?

### Explicação da função usada -> train_test_split
- parametros train_size_split
- arrays : nomes dos atributos previsores e alvo
- teste_size: tamanho em porcentagem dos daods de teste. Deault é none
- train_size: tamanho em porcentagem dos dados de treinamento.defautl é none
- random_state: nomeação de um estado aleatorio
- shuffle:embralhamento dos dados aleatorios. Assiciado com o random_state ocorre o mesmo embaralhamento sempre.Default é true
- stratify: Possibilidade de dividir os dados de forma estratificada.Defaut é none(nesse caso é matido a proporção,isto é, se tem 30% de zeros e 70% de 1 no dataframa, na separação em treinamento e teste se mantera essa proporção).

In [77]:
## pode ser alterado, ate achar um previsor com maior porcentagem
## aqui a função entra nas varivaeis de forma padrao
## TESTAR TODOS PREVISORES PARA VER QUAL É MELHOR
## ALVO É PADRÃO
x_treino, x_teste, y_treino, y_teste = train_test_split(previsores3_esc, alvo, test_size= 0.3, random_state=0)


#### alvo = variável que se pretende atingir (tem ou não doença cardíaca).
#### previsores = conjunto de variáveis previsoras com as variáveis categóricas transformadas em numéricas manualmente, sem escalonar.
#### previsores_esc = conjunto de variáveis previsoras com as variáveis categóricas transformadas em numéricas, escalonada.
#### previsores2 = conjunto de variáveis previsoras com as variáveis categóricas transformadas em numéricas pelo labelencoder.
#### previsores3 = conjunto de variáveis previsoras transformadas pelo labelencoder e onehotencoder, sem escalonar.
#### previsores3_esc = conjunto de variáveis previsoras transformadas pelo labelencoder e onehotencoder escalonada.

In [78]:
x_treino.shape

(641, 20)

In [79]:
x_teste.shape

(276, 20)

In [80]:
y_treino.shape

(641,)

In [81]:
y_teste.shape

(276,)

# NAIVE BAYES

#### Vantagens:

- É computacionalmente eficiente e rápido para treinar e prever.
- Funciona bem com grandes conjuntos de dados.
- É robusto em relação a dados faltantes.
- Pode lidar com problemas de classificação multiclasse.
- É especialmente adequado para problemas de classificação de texto e mineração de dados.

#### Desvantagens:

- Pressupõe independência condicional entre os recursos, o que nem sempre é verdade na prática.
- Pode não funcionar bem quando há interações complexas entre os recursos.
- É sensível a features irrelevantes ou raras que podem afetar negativamente as previsões.
- Tende a ser menos preciso do que outros algoritmos mais complexos, como redes neurais ou SVM.m




In [94]:
from sklearn.naive_bayes import GaussianNB

In [95]:
naive = GaussianNB()
naive.fit(x_treino, y_treino)

GaussianNB()

In [96]:
## esse usa dentro da função - para comparar com o valor original x e y teste

previsoes_naive = naive.predict(x_teste)
previsoes_naive

array([1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1], dtype=int64)

In [97]:
y_teste

array([1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1], dtype=int64)

In [98]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [99]:
## acuracia para ver quanto em % quanto foi de acerto.
accuracy_score(y_teste, previsoes_naive)

0.8478260869565217

In [100]:
## usando no print
## e
print("Acurácia: %.2f%%" % (accuracy_score(y_teste, previsoes_naive) * 100))

Acurácia: 84.78%


In [101]:
##confusion_matrix? -> consultar o metodo para ver melhot as informaçoes

##########################################
# PREVISORES3_ESC
##--> os acertos são 100 e 134 -  que são 84 % dos  acertos
# 100 dos acertos a pessoas que NÂO tem tendencia a doenças cardiacas
# 21 pessoas -> não tem, mas tem tendencia
# 21 pessoas -> tem tendencia , mas nao tem
# 134 pessoas -> pessoa quye tem tendencias
confusion_matrix(y_teste, previsoes_naive)

array([[100,  21],
       [ 21, 134]], dtype=int64)

In [102]:
print(classification_report(y_teste, previsoes_naive))

              precision    recall  f1-score   support

           0       0.83      0.83      0.83       121
           1       0.86      0.86      0.86       155

    accuracy                           0.85       276
   macro avg       0.85      0.85      0.85       276
weighted avg       0.85      0.85      0.85       276



### Análise dados de treino

In [103]:
previsoes_treino =  naive.predict(x_treino)
previsoes_treino 

array([1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1,

In [104]:
## lembrar que se o treino tiver muito maiss acertos do que o teste pode ser um problema
## chamado isso de overfit no caso, mas aqui comparando os dois esta tudo certo
accuracy_score(y_treino, previsoes_treino)

0.8611544461778471

In [105]:
print("Acurácia de treino: %.2f%%" % (accuracy_score(y_treino, previsoes_treino) * 100))

Acurácia de treino: 86.12%


In [106]:
confusion_matrix(y_treino, previsoes_treino)

array([[248,  41],
       [ 48, 304]], dtype=int64)

In [107]:
print(classification_report(y_teste, previsoes_naive))

              precision    recall  f1-score   support

           0       0.83      0.83      0.83       121
           1       0.86      0.86      0.86       155

    accuracy                           0.85       276
   macro avg       0.85      0.85      0.85       276
weighted avg       0.85      0.85      0.85       276



#### VALIDAÇÃO CRUZADA

In [ ]:
## depois de escolher qual variavel roda melhor na função do naive bayes
## AQUI a função naive bayes será lançada varias vezes para achar a media de acertos %


In [116]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

In [117]:
## separando os dados em folds
# N_SPLITS vai montar 30 caixa ou 30 vezes a analise para ter uma media de acertos
kfold = KFold(n_splits=30, shuffle=True, random_state=5)

In [120]:
## criando o modelo
modelo = GaussianNB()
resultado = cross_val_score(modelo, previsores3_esc, alvo, cv = kfold)

In [119]:
cross_val_score?

In [121]:
## usamos a media e o desvio padrao
print('Acuracia Media: %.2f%%' % (resultado.mean() * 100.0))

Acuracia Media: 85.17%


In [155]:
print("Acuracia: %.2f%%" % (accuracy_score(y_teste, previsoes_svm) * 100.0))

Acuracia: 86.23%


In [156]:
confusion_matrix(y_teste, previsoes_svm)

array([[ 99,  22],
       [ 16, 139]], dtype=int64)

In [157]:
print(classification_report(y_teste, previsoes_svm))

              precision    recall  f1-score   support

           0       0.86      0.82      0.84       121
           1       0.86      0.90      0.88       155

    accuracy                           0.86       276
   macro avg       0.86      0.86      0.86       276
weighted avg       0.86      0.86      0.86       276



# SVM - máquina de Vetor de suporte

#### Vantagem
- Não é influenciado por dados discrepantes - outliers por exemplo
- Muito efetivo para datasets grandes
- consegue aprender com caracteristicas não pertencentes aos dados
- É menos propenso a overfitting quando comparado a outros algoritmos de aprendizado de máquina.
- É eficaz na resolução de problemas de classificação binária.

#### DESVANTEGENS
- dificil interpretação teorica devido a matematica complexa
- Dificil visualização grafica
- È lento comparado aos outros algoritmos.
- Deve se ter um grande cuidado com as definições dos hiperparametro para evitar overfitiing e underfitting

In [82]:
from sklearn.svm import SVC

In [83]:
## houve uma mudança no kernel para 'linear' aonde melhorou a analise ate, mas por padrao RBF é usado.
## signmoind, poly, linear, etc sao alguns kernel existente para analise
svm = SVC(kernel='rbf', random_state=1, C = 2)
svm.fit(x_treino, y_treino)

SVC(C=2, random_state=1)

In [84]:
## houve uma mudança no kernel para 'linear' aonde melhorou a analise ate, mas por padrao RBF é usado.
## signmoind, poly, linear, etc sao alguns kernel existente para analise
svm = SVC(kernel='rbf', random_state=1, C = 2)
svm.fit(x_treino, y_treino)

SVC(C=2, random_state=1)

In [85]:
previsoes_svm = svm.predict(x_teste)
previsoes_svm

array([1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1], dtype=int64)

In [86]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [87]:
print("Acuracia: %.2f%%" % (accuracy_score(y_teste, previsoes_svm) * 100.0))

Acuracia: 86.23%


#### Análise dados de treino

In [88]:
previsoes_treino = svm.predict(x_treino)
previsoes_treino

array([1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1,

In [89]:
accuracy_score(y_treino, previsoes_treino)

0.9282371294851794

In [90]:
confusion_matrix(y_treino, previsoes_treino)

array([[257,  32],
       [ 14, 338]], dtype=int64)

#### Validação cruzada

In [91]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

In [92]:
## separando os dados em folds
kfold = KFold(n_splits=30, shuffle=True, random_state=5)

In [93]:
# criando o modelo
## quanto maior for o C mais o risco de overfitting
modelo = SVC(kernel='rbf', random_state=1, C=2.0)
resultado = cross_val_score(modelo, previsores3_esc, alvo, cv=kfold)

In [94]:
#usasdmos a media e o desvio padrão
print("Acuracia Media: %.2f%%" % (resultado.mean() * 100))

Acuracia Media: 85.72%


# Resultado Final

- NAIVE BAYES = 84,78 (TREINO E TESTE) - 234 acertos e 85,16 % (validação cruzada), previsores3_esc

- SVM = 86,23% - 238 ACERTOS E 85,72%, (validação cruzada): previsores3_esc

- foi utilizado diversos algoritmos para realização desse projeto. Esses foram os melhores e aqui comparados para realização do projeto de classificação. 


- Proximo passo o caso sera tratado no Power Bi para analise visual no Dashboard interativo